version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy
permissions:
  - object: /home/ubuntu/deploy/scripts
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: ubuntu
