version: 0.2

env:
  variables:
    REPO_NAME: node-repo
    CONTAINER_NAME: node

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 099199746132.dkr.ecr.eu-west-1.amazonaws.com
      - export REPO_URI=099199746132.dkr.ecr.eu-west-1.amazonaws.com/$REPO_NAME
      - export IMAGE_TAG=latest

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $CONTAINER_NAME .
      - echo Tagging the Docker image...
      - docker tag $CONTAINER_NAME:latest $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Creating imagedefinitions.json for ECS deployment...
      - echo '[{"name":"'"$CONTAINER_NAME"'","imageUri":"'"$REPO_URI:$IMAGE_TAG"'"}]' > imagedefinitions.json
      - echo Contents of imagedefinitions.json:
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
