version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update
      - sudo apt-get install -y docker
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.eu-west-1.amazonaws.com
      - REPO_URI=<AWS_ACCOUNT_ID>.dkr.ecr.eu-west-1.amazonaws.com/<ECR_REPOSITORY_NAME>
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $REPO_URI:$IMAGE_TAG .
      - docker tag $REPO_URI:$IMAGE_TAG $REPO_URI:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push $REPO_URI:$IMAGE_TAG
      - docker push $REPO_URI:latest
      - echo "Writing image definition file..."
      - printf '[{"name":"node-app","imageUri":"%s"}]' $CONTAINER_NAME $REPO_URI:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
