version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 099199746132.dkr.ecr.eu-west-1.amazonaws.com/demo_repo
      - export REPO_URI="099199746132.dkr.ecr.eu-west-1.amazonaws.com/demo_repo"
      - export IMAGE_TAG="latest"

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t node .
      - echo "Tagging image as latest..."
      - docker tag node:latest $REPO_URI:$IMAGE_TAG
      - echo "Pushing image to ECR..."
      - docker push $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Writing image definition file...
      - echo '[{"name":"node","imageUri":"'$REPO_URI:$IMAGE_TAG'"}]' > imagedefinitions.json
      - cat imagedefinitions.json  # Debugging: check the file contents

artifacts:
  files:
    - scripts/**
    - appspec.yml
    - image_uri.txt
  discard-paths: no

