version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 099199746132.dkr.ecr.eu-west-1.amazonaws.com/demo_repo
      - export REPO_URI="099199746132.dkr.ecr.eu-west-1.amazonaws.com/demo_repo"
      - export IMAGE_TAG="latest"

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t node .
      - echo "Tagging image as latest..."
      - docker tag node:latest $REPO_URI:$IMAGE_TAG
      - docker push $REPO_URI:$IMAGE_TAG
      - echo "Writing image URI to file..."
      - echo '[{"name":"node","imageUri":"'$REPO_URI:$IMAGE_TAG'"}]' > imagedefinitions.json

  post_build:
    commands:
      - echo Checking Docker images...
      - docker images
      - echo Uploading artifacts to S3...
      - aws s3 cp imagedefinitions.json s3://demobucket1603/   # Ensures it gets uploaded

artifacts:
  files:
    - appspec.yml
    - imagedefinitions.json
    - scripts/**    # This ensures the entire scripts folder is included
  discard-paths: no

