version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 099199746132.dkr.ecr.eu-west-1.amazonaws.com/demo_repo
      - export REPO_URI="099199746132.dkr.ecr.eu-west-1.amazonaws.com/demo_repo"
      - export IMAGE_TAG="latest"

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t node .
      - echo "Tagging image as latest..."
      - docker tag node:latest 099199746132.dkr.ecr.eu-west-1.amazonaws.com/demo_repo:latest
      - docker push 099199746132.dkr.ecr.eu-west-1.amazonaws.com/demo_repo:latest
      - echo "Creating imagedefinitions.json..."
      - echo '[{"name":"node","imageUri":"'"$REPO_URI:$IMAGE_TAG"'"}]' > imagedefinitions.json

  post_build:
    commands:
      - echo Checking Docker images...
      - docker images
      - echo Pushing Docker image to Amazon ECR...
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Ensuring all files exist before upload...
      - ls -la
      - ls -R scripts/

artifacts:
  files:
    - appspec.yml
    - imagedefinitions.json
    - scripts/**  # Ensures the entire scripts directory is included
  discard-paths: no  # Ensures folder structure is retained
