version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install -y docker
  pre_build:
    commands:
      - echo "Checking AWS credentials..."
      - aws sts get-caller-identity # Debugging IAM role access
      - echo "Logging in to Amazon ECR..."
      - export AWS_REGION="eu-west-1"
      - export AWS_ACCOUNT_ID="099199746132"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - REPOSITORY URI-SAWS_ACCOUNT_ID.dkr.ecr.SAWS_DEFAULT_REGION.amazonaws.com/SIMAGE_REPO_NAME
      - IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $REPO_URI:$IMAGE_TAG .
      - docker tag $REPO_URI:$IMAGE_TAG $REPO_URI:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push $REPO_URI:$IMAGE_TAG
      - docker push $REPO_URI:latest
      - echo "Writing image definition file..."
      - printf '[{"name":"node-app","imageUri":"%s"}]' $CONTAINER_NAME $REPO_URI:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
