version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 099199746132.dkr.ecr.eu-west-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t node .
      - docker tag node:latest 099199746132.dkr.ecr.eu-west-1.amazonaws.com/node-repo:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 099199746132.dkr.ecr.eu-west-1.amazonaws.com/node-repo:latest
      - echo Writing imagedefinitions.json...
      - printf '[{"name":"node","imageUri":"099199746132.dkr.ecr.eu-west-1.amazonaws.com/node-repo:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
