on: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install -y docker jq # Added jq for parsing JSON if needed
  pre_build:
    commands:
      - echo "Cleaning up old Docker images..."
      - docker system prune -a -f
      - echo "Checking AWS credentials..."
      - aws sts get-caller-identity # Debugging IAM role access
      - echo "Logging in to Amazon ECR..."
      - export AWS_REGION="eu-west-1"
      - export AWS_ACCOUNT_ID="099199746132"
      - export REPO_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/demo_repo"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO_URI
      - echo "Verifying ECR login..."
      - docker info
      - export IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t $REPO_URI:$IMAGE_TAG .
      - docker tag $REPO_URI:$IMAGE_TAG $REPO_URI:latest
  post_build:
    commands:
      - chmod +r appspec.yml scripts/*.sh
      - chmod +x scripts/*.sh
      - echo "Verifying required files before artifact upload..."
      - ls -lah
      - ls -lah scripts/
      - echo "Listing all files before uploading artifacts..."
      - find . -type f
      - zip -r debug_artifacts.zip appspec.yml scripts/ imagedefinitions.json
      - unzip -l debug_artifacts.zip
      - echo "Pushing the Docker image to Amazon ECR..."
      - docker push $REPO_URI:$IMAGE_TAG
      - docker push $REPO_URI:latest
      - echo "Writing image definition file..."
      - echo '[{"name":"node","imageUri":"'"$REPO_URI:latest"'"}]' > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - appspec.yml
    - scripts/*.sh
    - imagedefinitions.json
