version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking AWS credentials..."
      - aws sts get-caller-identity # Debugging IAM role access
      - echo "Logging in to Amazon ECR..."
      - export AWS_REGION="eu-west-1"
      - export AWS_ACCOUNT_ID="099199746132"
      - export REPO_URI="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/demo_repo"
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPO_URI
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $REPO_URI:latest .
      - echo "Tagging Docker image..."
      - docker tag $REPO_URI:latest $REPO_URI:$(date +%Y%m%d%H%M%S)

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $REPO_URI:latest
      - echo "Writing image definition file..."
      - printf '[{"name":"node","imageUri":"%s"}]' "$REPO_URI:latest" > imagedefinitions.json
      - cat imagedefinitions.json  # Debugging: Print the file content
      - echo "Build completed successfully!"

artifacts:
  files:
    - imagedefinitions.json
